site_name: Beyond LaTeX Templates
site_url: https://hantang.github.io/latex-templates
site_author: hantang
site_description: "Collect awesome latex* templates (mainly thesis)..."
# docs_dir: docs/

# Repository
repo_name: hantang/latex-templates
repo_url: https://github.com/hantang/latex-templates
# edit_uri: tree/main

copyright: Copyright &copy; 2023 Hantang

theme:
  name: material
  language: zh
  highlightjs: true
  icon:
    logo: material/notebook
  font:
    text: Helvetica Neue # Roboto
    code: Roboto Mono
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - toc.follow
    - content.tabs.link
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotations

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/tablesort-5.3.0/dist/tablesort.min.js
  - assets/javascripts/tablesort-5.3.0/dist/sorts/tablesort.date.min.js
  - assets/javascripts/tablesort-5.3.0/dist/sorts/tablesort.number.min.js
  - assets/javascripts/extra.js

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - table-reader

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hantang

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_truly_sane_lists
  - tables
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - 主页:
    - 说明: index.md
    - 中国内地（大陆）高校: 1.1-zh1.md
    - 中国港澳台地区高校: 1.2-zh2.md
    - 美国地区高校: 1.3-us.md
    - 其他国家（地区）高校: 1.4-else.md
    - 其他LaTeX模板: 2.0-latex.md
    - 非LaTeX模板: 3.0-more.md
    - 补充资料: 4.0-supplement.md
    - LaTeX资源: 5.0-resource.md
  - 论文模板:
    - 中国内地（大陆）高校: 1.1-zh1.md
    - 中国港澳台地区高校: 1.2-zh2.md
    - 美国地区高校: 1.3-us.md
    - 其他国家（地区）高校: 1.4-else.md
  - 更多模版:
    - 其他LaTeX模板: 2.0-latex.md
    - 非LaTeX模板: 3.0-more.md
  - 更多资源:
    - 补充资料: 4.0-supplement.md
    - LaTeX资源: 5.0-resource.md
