name: Auto Update Stats

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Test
      run: |
        python -c "import requests; print(requests.__version__)"
    - name: Commit and push 
      run: |
        git diff
